### ISSUE TITLE
Mob Disguises (mobdisguises) has failed to correctly

### ISSUE THREAD

**Issue by 6371peter** [samolego/MobDisguises#10]
1.16.5Forge 36.1.31
mobdisguises 1.0.1
[crash-2021-07-05_13.13.51-fml.txt](https://github.com/samolego/MobDisguises/files/6761873/crash-2021-07-05_13.13.51-fml.txt)

**Comment by James103** [comment]
Can you please try with the latest MobDisguises 1.0.5 and Minecraft 1.17.1?
