### ISSUE TITLE
Launcher immediately shows crash message instead of starting up WITH THE MOD

### ISSUE THREAD

**Issue by StickyChannel92** [samolego/MobDisguises#13]
Launcher immediately shows a crash message, right after clicking on "Play" in the launcher. Without the mod, this is no issue.

**Comment by samolego** [comment]
Logs please :)

**Comment by StickyChannel92** [comment]
[crash-2021-09-16_23.26.20-client.txt](https://github.com/samolego/MobDisguises/files/7187088/crash-2021-09-16_23.26.20-client.txt)

**Comment by samolego** [comment]
Can you try removing `identity` mod?

**Comment by StickyChannel92** [comment]
There's no identity, since I just moved to another device. Anyways, leaving it out does not fix the problem.

**Comment by StickyChannel92** [comment]
Or is _this_ the log? It's called latest.log, which was done at 5:35am 9/21/2021
[latest.log](https://github.com/samolego/MobDisguises/files/7202447/latest.log)

**Comment by samolego** [comment]
> Or is _this_ the log? It's called latest.log, which was done at 5:35am 9/21/2021
> [latest.log](https://github.com/samolego/MobDisguises/files/7202447/latest.log)

This doesn't seem like whole log ...

**Comment by StickyChannel92** [comment]
So where would `identity` be? I don't seem to have it anymore. Leaving whatever the identity mod is doesn't work.

**Comment by James103** [comment]
> [crash-2021-09-16_23.26.20-client.txt](https://github.com/samolego/MobDisguises/files/7187088/crash-2021-09-16_23.26.20-client.txt)

That crash is a duplicate of https://github.com/Draylar/identity/issues/277.
