### ISSUE TITLE
Building version 1.0.4 fails with `Could not find xyz.nucleoid:common:1.0.7`

### ISSUE THREAD

**Issue by James103** [samolego/MobDisguises#14]
To reproduce:
1. Obtain a copy of the latest source code for this mod and download it into an empty directory.
2. Inside the directory holding the mod's source code, run `gradlew build`.
3. Notice that the build fails.

See: https://github.com/samolego/MobDisguises/runs/3777102566

**Comment by samolego** [comment]
That's what I'm bumping my head on atm :sweat_smile:

**Comment by James103** [comment]
As a workaround, instead of just `./gradlew build` directly, do the following instead:
1. Clone the repository from commit adac4e118fdbc21ca8b80bcea3d1fc7d951635c9.
2. Edit `gradle.properties` in any text editor and change the last line from `disguiselib_version = 1.0.7` to `disguiselib_version = 1.0.8`.
3. Save the file.
4. Only then, run `./gradlew build`.
5. If `./gradlew build` hangs for more than 5 minutes on a single task, terminate (`CTRL+C`) and restart the command.

**Comment by samolego** [comment]
Yeah, that's why 1.0.8 was released.
