### ISSUE TITLE
Ability to hide names of NPCs disguised as players?

### ISSUE THREAD

**Issue by maxheyn** [samolego/MobDisguises#20]
Currently, as far as I am aware, whenever you disguise an NPC as a player, the name shows above. You can rename them with nametags but that doesn't update in real time, you first have to disguise them again for it to apply. (Not a huge deal, can be worked around.)

However, I'd like to be able to hide the names of these player-disguised NPCs, since names are quite obtrusive as they render above everything and if used as decoration it'd be nice to be able to hide them.

![image](https://user-images.githubusercontent.com/16215993/142934174-9f04f4d2-0e62-4bb2-967b-1fa7a1d7a0b8.png)

**Comment by samolego** [comment]
Hi, this is kinda out of scope for this mod ... You can use vanilla team system to hide names afaik and add the npcs to that team or use the other mod that I'm developing, focused only on NPCs, https://github.com/samolego/Taterzens
