### ISSUE TITLE
Incompatible with latest DisguiseLib 1.2.1 on Minecraft 1.18.1

### ISSUE THREAD

**Issue by James103** [samolego/MobDisguises#23]
Currently, MobDisguises is incompatible with DisguiseLib 1.2.1 and Minecraft 1.18.1, with the latest supported version apparently being DisguiseLib 1.1.x and Minecraft 1.18-pre1. Will you please update this mod to remain compatible with the newest versions?

**Comment by samolego** [comment]
Oh, sure, I forgot to push the update 😅

**Comment by samolego** [comment]
Sorry for the delay, pushed now
